// cellStore — v2 tiered storage, backed by an R2 binding (env.BUCKET).
//
// Object keys are `{tier}/{tier}_{lat}_{lon}.csv.gz`, matching what the frontend
// fetches and what the producer / upload scripts (scripts/era5_pipeline/) write.
// Storage notes:
//
//   - reads/writes go through the R2 binding (env.BUCKET);
//   - freshness is the object's `uploaded` timestamp (R2's equivalent of an mtime
//     / Last-Modified), which ensure-fresh compares against its TTLs;
//   - no atomic-rename dance: R2 put() is already atomic (a reader sees the
//     whole old or whole new object, never a partial one).
//
// Objects are stored gzip-compressed with the right Content-Type/Encoding so the
// public R2 URL serves a browser-gunzippable file: the browser auto-gunzips via
// Content-Encoding: gzip.

const TIERS = ['archive', 'recent', 'forecast'];

// Cache-Control per tier, stored as object httpMetadata so R2 serves it as the
// origin header. This is what keeps the volatile tiers fresh now that the data
// domain (data.weatherbaseline.com) sits behind Cloudflare's cache: .gz is on
// the default-cacheable extension list, so without an explicit header the edge
// would hold recent/forecast for ~2h (and browsers would heuristically cache
// off Last-Modified) after ensure-fresh rewrites them. The Worker only ever
// writes recent/forecast (both no-store); the archive entry is here only to
// mirror the producer (r2_upload.py). archive is `no-cache` — not a fixed day —
// because the trailing-year top-up rewrites the archive tail and deletes the
// cell's recent object once archive covers it, so a stale archive would strand
// those days; revalidating via ETag keeps it fresh cheaply. Keep in sync with
// r2_upload.py (the producer-side upload path).
const CACHE_CONTROL = {
  archive: 'public, no-cache',
  recent: 'no-store',
  forecast: 'no-store',
};

const SCHEMA = ['date', 'tmax_C', 'tmin_C', 'precip_mm', 'wind_max_ms'];

/** Snap a coordinate to the fixed 0.1° ERA5-Land grid: round(coord*10)/10. */
function snap(coord) {
  return Math.round(coord * 10) / 10;
}

/** Snapped "lat_lon" identity for a cell — the coordinate part of every object
 * key, and the membership token for the curated-cell allowlist (cellKeys.js).
 * Generated by scripts/gen-cell-keys.mjs with THIS function, so the allowlist
 * and a live request snap to byte-identical strings. */
function cellKey(lat, lon) {
  return `${snap(lat).toFixed(1)}_${snap(lon).toFixed(1)}`;
}

/** Object key for a tier + snapped cell, e.g. archive/archive_32.8_35.1.csv.gz. */
function objectKey(tier, lat, lon) {
  return `${tier}/${tier}_${cellKey(lat, lon)}.csv.gz`;
}

/**
 * Age in milliseconds of a tier object's last write, or Infinity if absent.
 * ensure-fresh compares this against its TTLs. We use R2's `uploaded` timestamp
 * (the analogue of the FS mtime the Node version used). head() is a Class B op
 * (cheap, 10M/mo free) and doesn't transfer the body.
 */
async function ageMs(bucket, tier, lat, lon) {
  const obj = await bucket.head(objectKey(tier, lat, lon));
  if (!obj) return Infinity;
  return Date.now() - obj.uploaded.getTime();
}

/**
 * Read a tier object into an array of row objects keyed by SCHEMA, or [] if the
 * object doesn't exist yet. The stored body is gzip; we decompress with the
 * runtime's DecompressionStream (no Node zlib in the Workers runtime).
 */
async function readRows(bucket, tier, lat, lon) {
  const obj = await bucket.get(objectKey(tier, lat, lon));
  if (!obj) return [];
  const text = await gunzipToText(obj.body);
  return parseCsv(text);
}

/**
 * Write rows to a tier object as gzip CSV. Rows are sorted by date and
 * serialized in SCHEMA column order. R2 put() is atomic, so no temp/rename.
 * Sets Content-Type/Encoding so the public R2 URL serves a browser-gunzippable
 * file (text/csv + Content-Encoding: gzip).
 */
async function writeRows(bucket, tier, lat, lon, rows) {
  const sorted = [...rows].sort((a, b) => a.date.localeCompare(b.date));
  const gz = await gzipText(serializeCsv(sorted));
  await bucket.put(objectKey(tier, lat, lon), gz, {
    httpMetadata: {
      contentType: 'text/csv; charset=utf-8',
      contentEncoding: 'gzip',
      cacheControl: CACHE_CONTROL[tier],
    },
  });
}

/**
 * Last (max) date present in a tier object, or null if the object is empty/
 * absent. Used by the recent refresh to anchor its start_date to the day after
 * the archive ends, so recent always spans the full archive→frontier seam
 * rather than a fixed trailing window. Reads the whole object (rows are sorted
 * on write, so the last row is the max date) — fine at recent's once-per-24h
 * cadence.
 */
async function lastDate(bucket, tier, lat, lon) {
  const rows = await readRows(bucket, tier, lat, lon);
  return rows.length ? rows[rows.length - 1].date : null;
}

/**
 * Merge new rows into an existing tier object by date, last-wins, then write.
 * Used by the recent tier's append-only refresh: an overlapping re-run is
 * idempotent and a skipped run self-heals on the next call.
 */
async function mergeRows(bucket, tier, lat, lon, newRows) {
  const existing = await readRows(bucket, tier, lat, lon);
  const byDate = new Map();
  for (const r of existing) byDate.set(r.date, r);
  for (const r of newRows) byDate.set(r.date, r); // last-wins
  await writeRows(bucket, tier, lat, lon, [...byDate.values()]);
}

// --- gzip helpers (Workers runtime: Compression/DecompressionStream) --------

async function gzipText(text) {
  const cs = new CompressionStream('gzip');
  const stream = new Response(text).body.pipeThrough(cs);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

async function gunzipToText(body) {
  const ds = new DecompressionStream('gzip');
  const stream = body.pipeThrough(ds);
  return new Response(stream).text();
}

// --- CSV helpers (no quoting needed: all fields are dates/numbers) ----------
// Format must stay identical to the producer / upload scripts in
// scripts/era5_pipeline/ so archive + live tiers parse the same.

function parseCsv(text) {
  const lines = text.trim().split('\n');
  if (lines.length <= 1) return [];
  const header = lines[0].split(',');
  return lines.slice(1).map((line) => {
    const cells = line.split(',');
    const row = {};
    header.forEach((col, i) => {
      row[col] = cells[i];
    });
    return row;
  });
}

function serializeCsv(rows) {
  const out = [SCHEMA.join(',')];
  for (const r of rows) {
    out.push(SCHEMA.map((col) => (r[col] ?? '')).join(','));
  }
  return out.join('\n') + '\n';
}

export {
  TIERS,
  SCHEMA,
  snap,
  cellKey,
  objectKey,
  ageMs,
  readRows,
  writeRows,
  mergeRows,
  lastDate,
};
